services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - ENV=development
      - PORT=${API_GATEWAY_PORT}
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - USER_SERVICE_URL=user-service:${USER_SERVICE_PORT}
      - CHAT_SERVICE_URL=chat-service:${CHAT_SERVICE_PORT}
      - AUTH_SERVICE_URL=auth-service:${AUTH_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      - redis
      - user-service
      - chat-service
      - auth-service
    networks:
      - ${NETWORK_NAME}
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - ${NETWORK_NAME}
  post_service_db:
    image: postgres:16
    container_name: post_service_db
    environment:
      POSTGRES_DB: post_service_db
      POSTGRES_USER: post_service
      POSTGRES_PASSWORD: post_service
    ports:
      - "5434:5432"
    volumes:
      - post_service_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U post_service -d post_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${USER_DB_PORT}:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

  chat-db:
    image: postgres:15-alpine
    container_name: chat-db
    environment:
      POSTGRES_DB: ${CHAT_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${CHAT_DB_PORT}:5432"
    volumes:
      - chat_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped
  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_NAME=${USER_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GRPC_PORT=${USER_SERVICE_PORT}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - user-db
    networks:
      - ${NETWORK_NAME}

  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_NAME=${AUTH_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GRPC_PORT=${AUTH_SERVICE_PORT}
      - USER_SERVICE_ADDR=user-service:${USER_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      - auth-db
      - user-service
    networks:
      - ${NETWORK_NAME}

  chat-service:
    build:
      context: ./chat_service
      dockerfile: Dockerfile
    container_name: chat-service
    environment:
      - DB_HOST=chat-db
      - DB_PORT=5432
      - DB_NAME=${CHAT_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GRPC_PORT=${CHAT_SERVICE_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=1
      - REDIS_CHANNEL=chat_messages
      - REDIS_URL=redis:6379
    ports:
      - "${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}"
    depends_on:
      - chat-db
      - redis
    networks:
      - ${NETWORK_NAME}

volumes:
  redis_data:
  user_data:
  auth_data:
  chat_data:
  post_service_db_data:


networks:
  my-app-network:
    driver: bridge
