// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MentorProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WithdrawalAddress *string                `protobuf:"bytes,2,opt,name=withdrawal_address,json=withdrawalAddress,proto3,oneof" json:"withdrawal_address,omitempty"`
	Rating            float64                `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Description       *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MentorProfile) Reset() {
	*x = MentorProfile{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorProfile) ProtoMessage() {}

func (x *MentorProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorProfile.ProtoReflect.Descriptor instead.
func (*MentorProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *MentorProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MentorProfile) GetWithdrawalAddress() string {
	if x != nil && x.WithdrawalAddress != nil {
		return *x.WithdrawalAddress
	}
	return ""
}

func (x *MentorProfile) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MentorProfile) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *MentorProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type StudentProfile struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LearningGoals          *string                `protobuf:"bytes,2,opt,name=learning_goals,json=learningGoals,proto3,oneof" json:"learning_goals,omitempty"`
	PreferredLearningStyle *string                `protobuf:"bytes,3,opt,name=preferred_learning_style,json=preferredLearningStyle,proto3,oneof" json:"preferred_learning_style,omitempty"`
	CreatedAt              string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StudentProfile) Reset() {
	*x = StudentProfile{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentProfile) ProtoMessage() {}

func (x *StudentProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentProfile.ProtoReflect.Descriptor instead.
func (*StudentProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *StudentProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StudentProfile) GetLearningGoals() string {
	if x != nil && x.LearningGoals != nil {
		return *x.LearningGoals
	}
	return ""
}

func (x *StudentProfile) GetPreferredLearningStyle() string {
	if x != nil && x.PreferredLearningStyle != nil {
		return *x.PreferredLearningStyle
	}
	return ""
}

func (x *StudentProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TeachingSkill struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SkillId           string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkillName         string                 `protobuf:"bytes,3,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	ProficiencyLevel  string                 `protobuf:"bytes,4,opt,name=proficiency_level,json=proficiencyLevel,proto3" json:"proficiency_level,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TeachingSkill) Reset() {
	*x = TeachingSkill{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeachingSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeachingSkill) ProtoMessage() {}

func (x *TeachingSkill) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeachingSkill.ProtoReflect.Descriptor instead.
func (*TeachingSkill) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *TeachingSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *TeachingSkill) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeachingSkill) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *TeachingSkill) GetProficiencyLevel() string {
	if x != nil {
		return x.ProficiencyLevel
	}
	return ""
}

func (x *TeachingSkill) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *TeachingSkill) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LearningSkill struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SkillId          string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkillName        string                 `protobuf:"bytes,3,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	ProficiencyLevel string                 `protobuf:"bytes,4,opt,name=proficiency_level,json=proficiencyLevel,proto3" json:"proficiency_level,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LearningSkill) Reset() {
	*x = LearningSkill{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningSkill) ProtoMessage() {}

func (x *LearningSkill) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningSkill.ProtoReflect.Descriptor instead.
func (*LearningSkill) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *LearningSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *LearningSkill) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LearningSkill) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *LearningSkill) GetProficiencyLevel() string {
	if x != nil {
		return x.ProficiencyLevel
	}
	return ""
}

func (x *LearningSkill) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MentorUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalAddress *string                `protobuf:"bytes,1,opt,name=withdrawal_address,json=withdrawalAddress,proto3,oneof" json:"withdrawal_address,omitempty"`
	Description       *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MentorUpdate) Reset() {
	*x = MentorUpdate{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorUpdate) ProtoMessage() {}

func (x *MentorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorUpdate.ProtoReflect.Descriptor instead.
func (*MentorUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *MentorUpdate) GetWithdrawalAddress() string {
	if x != nil && x.WithdrawalAddress != nil {
		return *x.WithdrawalAddress
	}
	return ""
}

func (x *MentorUpdate) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type StudentUpdate struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LearningGoals          *string                `protobuf:"bytes,1,opt,name=learning_goals,json=learningGoals,proto3,oneof" json:"learning_goals,omitempty"`
	PreferredLearningStyle *string                `protobuf:"bytes,2,opt,name=preferred_learning_style,json=preferredLearningStyle,proto3,oneof" json:"preferred_learning_style,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StudentUpdate) Reset() {
	*x = StudentUpdate{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentUpdate) ProtoMessage() {}

func (x *StudentUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentUpdate.ProtoReflect.Descriptor instead.
func (*StudentUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *StudentUpdate) GetLearningGoals() string {
	if x != nil && x.LearningGoals != nil {
		return *x.LearningGoals
	}
	return ""
}

func (x *StudentUpdate) GetPreferredLearningStyle() string {
	if x != nil && x.PreferredLearningStyle != nil {
		return *x.PreferredLearningStyle
	}
	return ""
}

type TeachingSkillUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SkillName         string                 `protobuf:"bytes,1,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	ProficiencyLevel  string                 `protobuf:"bytes,2,opt,name=proficiency_level,json=proficiencyLevel,proto3" json:"proficiency_level,omitempty"`
	YearsOfExperience int32                  `protobuf:"varint,3,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TeachingSkillUpdate) Reset() {
	*x = TeachingSkillUpdate{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeachingSkillUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeachingSkillUpdate) ProtoMessage() {}

func (x *TeachingSkillUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeachingSkillUpdate.ProtoReflect.Descriptor instead.
func (*TeachingSkillUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *TeachingSkillUpdate) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *TeachingSkillUpdate) GetProficiencyLevel() string {
	if x != nil {
		return x.ProficiencyLevel
	}
	return ""
}

func (x *TeachingSkillUpdate) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

type LearningSkillUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SkillName        string                 `protobuf:"bytes,1,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	ProficiencyLevel string                 `protobuf:"bytes,2,opt,name=proficiency_level,json=proficiencyLevel,proto3" json:"proficiency_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LearningSkillUpdate) Reset() {
	*x = LearningSkillUpdate{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningSkillUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningSkillUpdate) ProtoMessage() {}

func (x *LearningSkillUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningSkillUpdate.ProtoReflect.Descriptor instead.
func (*LearningSkillUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *LearningSkillUpdate) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *LearningSkillUpdate) GetProficiencyLevel() string {
	if x != nil {
		return x.ProficiencyLevel
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailResponse) Reset() {
	*x = GetUserByEmailResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailResponse) ProtoMessage() {}

func (x *GetUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*GetUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserByEmailResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type TeachingSkillsUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TeachingSkills []*TeachingSkillUpdate `protobuf:"bytes,1,rep,name=teaching_skills,json=teachingSkills,proto3" json:"teaching_skills,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TeachingSkillsUpdate) Reset() {
	*x = TeachingSkillsUpdate{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeachingSkillsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeachingSkillsUpdate) ProtoMessage() {}

func (x *TeachingSkillsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeachingSkillsUpdate.ProtoReflect.Descriptor instead.
func (*TeachingSkillsUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *TeachingSkillsUpdate) GetTeachingSkills() []*TeachingSkillUpdate {
	if x != nil {
		return x.TeachingSkills
	}
	return nil
}

type LearningSkillsUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LearningSkills []*LearningSkillUpdate `protobuf:"bytes,1,rep,name=learning_skills,json=learningSkills,proto3" json:"learning_skills,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LearningSkillsUpdate) Reset() {
	*x = LearningSkillsUpdate{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningSkillsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningSkillsUpdate) ProtoMessage() {}

func (x *LearningSkillsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningSkillsUpdate.ProtoReflect.Descriptor instead.
func (*LearningSkillsUpdate) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *LearningSkillsUpdate) GetLearningSkills() []*LearningSkillUpdate {
	if x != nil {
		return x.LearningSkills
	}
	return nil
}

type UpdateProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName      *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName       *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Email          *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	AvatarUrl      *string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	MentorData     *MentorUpdate          `protobuf:"bytes,6,opt,name=mentor_data,json=mentorData,proto3,oneof" json:"mentor_data,omitempty"`
	StudentData    *StudentUpdate         `protobuf:"bytes,7,opt,name=student_data,json=studentData,proto3,oneof" json:"student_data,omitempty"`
	TeachingSkills *TeachingSkillsUpdate  `protobuf:"bytes,8,opt,name=teaching_skills,json=teachingSkills,proto3,oneof" json:"teaching_skills,omitempty"`
	LearningSkills *LearningSkillsUpdate  `protobuf:"bytes,9,opt,name=learning_skills,json=learningSkills,proto3,oneof" json:"learning_skills,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateProfileRequest) GetMentorData() *MentorUpdate {
	if x != nil {
		return x.MentorData
	}
	return nil
}

func (x *UpdateProfileRequest) GetStudentData() *StudentUpdate {
	if x != nil {
		return x.StudentData
	}
	return nil
}

func (x *UpdateProfileRequest) GetTeachingSkills() *TeachingSkillsUpdate {
	if x != nil {
		return x.TeachingSkills
	}
	return nil
}

func (x *UpdateProfileRequest) GetLearningSkills() *LearningSkillsUpdate {
	if x != nil {
		return x.LearningSkills
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProfileByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIdRequest) Reset() {
	*x = GetProfileByIdRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIdRequest) ProtoMessage() {}

func (x *GetProfileByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIdRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetProfileByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileByIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Mentor         *MentorProfile         `protobuf:"bytes,2,opt,name=mentor,proto3" json:"mentor,omitempty"`
	Student        *StudentProfile        `protobuf:"bytes,3,opt,name=student,proto3" json:"student,omitempty"`
	TeachingSkills []*TeachingSkill       `protobuf:"bytes,4,rep,name=teaching_skills,json=teachingSkills,proto3" json:"teaching_skills,omitempty"`
	LearningSkills []*LearningSkill       `protobuf:"bytes,5,rep,name=learning_skills,json=learningSkills,proto3" json:"learning_skills,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProfileByIdResponse) Reset() {
	*x = GetProfileByIdResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIdResponse) ProtoMessage() {}

func (x *GetProfileByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIdResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetProfileByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetProfileByIdResponse) GetMentor() *MentorProfile {
	if x != nil {
		return x.Mentor
	}
	return nil
}

func (x *GetProfileByIdResponse) GetStudent() *StudentProfile {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *GetProfileByIdResponse) GetTeachingSkills() []*TeachingSkill {
	if x != nil {
		return x.TeachingSkills
	}
	return nil
}

func (x *GetProfileByIdResponse) GetLearningSkills() []*LearningSkill {
	if x != nil {
		return x.LearningSkills
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // бинарные данные изображения
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "image/jpeg", "image/png", и другие
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *UploadAvatarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadAvatarRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *UploadAvatarRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadAvatarRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *UploadAvatarResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type DeleteAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarRequest) Reset() {
	*x = DeleteAvatarRequest{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarRequest) ProtoMessage() {}

func (x *DeleteAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteAvatarRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteAvatarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteAvatarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\auser.v1\"\xc3\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\r\n" +
	"\v_avatar_url\"\xe1\x01\n" +
	"\rMentorProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\x12withdrawal_address\x18\x02 \x01(\tH\x00R\x11withdrawalAddress\x88\x01\x01\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x01R\x06rating\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAtB\x15\n" +
	"\x13_withdrawal_addressB\x0e\n" +
	"\f_description\"\xe3\x01\n" +
	"\x0eStudentProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x0elearning_goals\x18\x02 \x01(\tH\x00R\rlearningGoals\x88\x01\x01\x12=\n" +
	"\x18preferred_learning_style\x18\x03 \x01(\tH\x01R\x16preferredLearningStyle\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAtB\x11\n" +
	"\x0f_learning_goalsB\x1b\n" +
	"\x19_preferred_learning_style\"\xde\x01\n" +
	"\rTeachingSkill\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x03 \x01(\tR\tskillName\x12+\n" +
	"\x11proficiency_level\x18\x04 \x01(\tR\x10proficiencyLevel\x12.\n" +
	"\x13years_of_experience\x18\x05 \x01(\x05R\x11yearsOfExperience\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xae\x01\n" +
	"\rLearningSkill\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x03 \x01(\tR\tskillName\x12+\n" +
	"\x11proficiency_level\x18\x04 \x01(\tR\x10proficiencyLevel\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x90\x01\n" +
	"\fMentorUpdate\x122\n" +
	"\x12withdrawal_address\x18\x01 \x01(\tH\x00R\x11withdrawalAddress\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01B\x15\n" +
	"\x13_withdrawal_addressB\x0e\n" +
	"\f_description\"\xaa\x01\n" +
	"\rStudentUpdate\x12*\n" +
	"\x0elearning_goals\x18\x01 \x01(\tH\x00R\rlearningGoals\x88\x01\x01\x12=\n" +
	"\x18preferred_learning_style\x18\x02 \x01(\tH\x01R\x16preferredLearningStyle\x88\x01\x01B\x11\n" +
	"\x0f_learning_goalsB\x1b\n" +
	"\x19_preferred_learning_style\"\x91\x01\n" +
	"\x13TeachingSkillUpdate\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x01 \x01(\tR\tskillName\x12+\n" +
	"\x11proficiency_level\x18\x02 \x01(\tR\x10proficiencyLevel\x12.\n" +
	"\x13years_of_experience\x18\x03 \x01(\x05R\x11yearsOfExperience\"a\n" +
	"\x13LearningSkillUpdate\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x01 \x01(\tR\tskillName\x12+\n" +
	"\x11proficiency_level\x18\x02 \x01(\tR\x10proficiencyLevel\"e\n" +
	"\x11CreateUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"-\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x12GetUserByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x13GetUserByIdResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\";\n" +
	"\x16GetUserByEmailResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"]\n" +
	"\x14TeachingSkillsUpdate\x12E\n" +
	"\x0fteaching_skills\x18\x01 \x03(\v2\x1c.user.v1.TeachingSkillUpdateR\x0eteachingSkills\"]\n" +
	"\x14LearningSkillsUpdate\x12E\n" +
	"\x0flearning_skills\x18\x01 \x03(\v2\x1c.user.v1.LearningSkillUpdateR\x0elearningSkills\"\xca\x04\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x03R\tavatarUrl\x88\x01\x01\x12;\n" +
	"\vmentor_data\x18\x06 \x01(\v2\x15.user.v1.MentorUpdateH\x04R\n" +
	"mentorData\x88\x01\x01\x12>\n" +
	"\fstudent_data\x18\a \x01(\v2\x16.user.v1.StudentUpdateH\x05R\vstudentData\x88\x01\x01\x12K\n" +
	"\x0fteaching_skills\x18\b \x01(\v2\x1d.user.v1.TeachingSkillsUpdateH\x06R\x0eteachingSkills\x88\x01\x01\x12K\n" +
	"\x0flearning_skills\x18\t \x01(\v2\x1d.user.v1.LearningSkillsUpdateH\aR\x0elearningSkills\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_emailB\r\n" +
	"\v_avatar_urlB\x0e\n" +
	"\f_mentor_dataB\x0f\n" +
	"\r_student_dataB\x12\n" +
	"\x10_teaching_skillsB\x12\n" +
	"\x10_learning_skills\"1\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15GetProfileByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa0\x02\n" +
	"\x16GetProfileByIdResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12.\n" +
	"\x06mentor\x18\x02 \x01(\v2\x16.user.v1.MentorProfileR\x06mentor\x121\n" +
	"\astudent\x18\x03 \x01(\v2\x17.user.v1.StudentProfileR\astudent\x12?\n" +
	"\x0fteaching_skills\x18\x04 \x03(\v2\x16.user.v1.TeachingSkillR\x0eteachingSkills\x12?\n" +
	"\x0flearning_skills\x18\x05 \x03(\v2\x16.user.v1.LearningSkillR\x0elearningSkills\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8d\x01\n" +
	"\x13UploadAvatarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"5\n" +
	"\x14UploadAvatarResponse\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl\".\n" +
	"\x13DeleteAvatarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x14DeleteAvatarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf5\x04\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"CreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\x12H\n" +
	"\vGetUserById\x12\x1b.user.v1.GetUserByIdRequest\x1a\x1c.user.v1.GetUserByIdResponse\x12Q\n" +
	"\x0eGetUserByEmail\x12\x1e.user.v1.GetUserByEmailRequest\x1a\x1f.user.v1.GetUserByEmailResponse\x12E\n" +
	"\n" +
	"DeleteUser\x12\x1a.user.v1.DeleteUserRequest\x1a\x1b.user.v1.DeleteUserResponse\x12Q\n" +
	"\x0eGetProfileById\x12\x1e.user.v1.GetProfileByIdRequest\x1a\x1f.user.v1.GetProfileByIdResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.user.v1.UpdateProfileRequest\x1a\x1e.user.v1.UpdateProfileResponse\x12K\n" +
	"\fUploadAvatar\x12\x1c.user.v1.UploadAvatarRequest\x1a\x1d.user.v1.UploadAvatarResponse\x12K\n" +
	"\fDeleteAvatar\x12\x1c.user.v1.DeleteAvatarRequest\x1a\x1d.user.v1.DeleteAvatarResponseB9Z7github.com/Sergey-1214/contracts_mentors/user/v1;userv1b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_user_proto_goTypes = []any{
	(*User)(nil),                   // 0: user.v1.User
	(*MentorProfile)(nil),          // 1: user.v1.MentorProfile
	(*StudentProfile)(nil),         // 2: user.v1.StudentProfile
	(*TeachingSkill)(nil),          // 3: user.v1.TeachingSkill
	(*LearningSkill)(nil),          // 4: user.v1.LearningSkill
	(*MentorUpdate)(nil),           // 5: user.v1.MentorUpdate
	(*StudentUpdate)(nil),          // 6: user.v1.StudentUpdate
	(*TeachingSkillUpdate)(nil),    // 7: user.v1.TeachingSkillUpdate
	(*LearningSkillUpdate)(nil),    // 8: user.v1.LearningSkillUpdate
	(*CreateUserRequest)(nil),      // 9: user.v1.CreateUserRequest
	(*CreateUserResponse)(nil),     // 10: user.v1.CreateUserResponse
	(*GetUserByIdRequest)(nil),     // 11: user.v1.GetUserByIdRequest
	(*GetUserByIdResponse)(nil),    // 12: user.v1.GetUserByIdResponse
	(*GetUserByEmailRequest)(nil),  // 13: user.v1.GetUserByEmailRequest
	(*GetUserByEmailResponse)(nil), // 14: user.v1.GetUserByEmailResponse
	(*TeachingSkillsUpdate)(nil),   // 15: user.v1.TeachingSkillsUpdate
	(*LearningSkillsUpdate)(nil),   // 16: user.v1.LearningSkillsUpdate
	(*UpdateProfileRequest)(nil),   // 17: user.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 18: user.v1.UpdateProfileResponse
	(*GetProfileByIdRequest)(nil),  // 19: user.v1.GetProfileByIdRequest
	(*GetProfileByIdResponse)(nil), // 20: user.v1.GetProfileByIdResponse
	(*DeleteUserRequest)(nil),      // 21: user.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 22: user.v1.DeleteUserResponse
	(*UploadAvatarRequest)(nil),    // 23: user.v1.UploadAvatarRequest
	(*UploadAvatarResponse)(nil),   // 24: user.v1.UploadAvatarResponse
	(*DeleteAvatarRequest)(nil),    // 25: user.v1.DeleteAvatarRequest
	(*DeleteAvatarResponse)(nil),   // 26: user.v1.DeleteAvatarResponse
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.GetUserByIdResponse.user:type_name -> user.v1.User
	0,  // 1: user.v1.GetUserByEmailResponse.user:type_name -> user.v1.User
	7,  // 2: user.v1.TeachingSkillsUpdate.teaching_skills:type_name -> user.v1.TeachingSkillUpdate
	8,  // 3: user.v1.LearningSkillsUpdate.learning_skills:type_name -> user.v1.LearningSkillUpdate
	5,  // 4: user.v1.UpdateProfileRequest.mentor_data:type_name -> user.v1.MentorUpdate
	6,  // 5: user.v1.UpdateProfileRequest.student_data:type_name -> user.v1.StudentUpdate
	15, // 6: user.v1.UpdateProfileRequest.teaching_skills:type_name -> user.v1.TeachingSkillsUpdate
	16, // 7: user.v1.UpdateProfileRequest.learning_skills:type_name -> user.v1.LearningSkillsUpdate
	0,  // 8: user.v1.GetProfileByIdResponse.user:type_name -> user.v1.User
	1,  // 9: user.v1.GetProfileByIdResponse.mentor:type_name -> user.v1.MentorProfile
	2,  // 10: user.v1.GetProfileByIdResponse.student:type_name -> user.v1.StudentProfile
	3,  // 11: user.v1.GetProfileByIdResponse.teaching_skills:type_name -> user.v1.TeachingSkill
	4,  // 12: user.v1.GetProfileByIdResponse.learning_skills:type_name -> user.v1.LearningSkill
	9,  // 13: user.v1.UserService.CreateUser:input_type -> user.v1.CreateUserRequest
	11, // 14: user.v1.UserService.GetUserById:input_type -> user.v1.GetUserByIdRequest
	13, // 15: user.v1.UserService.GetUserByEmail:input_type -> user.v1.GetUserByEmailRequest
	21, // 16: user.v1.UserService.DeleteUser:input_type -> user.v1.DeleteUserRequest
	19, // 17: user.v1.UserService.GetProfileById:input_type -> user.v1.GetProfileByIdRequest
	17, // 18: user.v1.UserService.UpdateProfile:input_type -> user.v1.UpdateProfileRequest
	23, // 19: user.v1.UserService.UploadAvatar:input_type -> user.v1.UploadAvatarRequest
	25, // 20: user.v1.UserService.DeleteAvatar:input_type -> user.v1.DeleteAvatarRequest
	10, // 21: user.v1.UserService.CreateUser:output_type -> user.v1.CreateUserResponse
	12, // 22: user.v1.UserService.GetUserById:output_type -> user.v1.GetUserByIdResponse
	14, // 23: user.v1.UserService.GetUserByEmail:output_type -> user.v1.GetUserByEmailResponse
	22, // 24: user.v1.UserService.DeleteUser:output_type -> user.v1.DeleteUserResponse
	20, // 25: user.v1.UserService.GetProfileById:output_type -> user.v1.GetProfileByIdResponse
	18, // 26: user.v1.UserService.UpdateProfile:output_type -> user.v1.UpdateProfileResponse
	24, // 27: user.v1.UserService.UploadAvatar:output_type -> user.v1.UploadAvatarResponse
	26, // 28: user.v1.UserService.DeleteAvatar:output_type -> user.v1.DeleteAvatarResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_user_proto_msgTypes[5].OneofWrappers = []any{}
	file_user_proto_msgTypes[6].OneofWrappers = []any{}
	file_user_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
